### ISSUE TITLE
Referencing an AbstractMediumSupply from an AbstractNetworkFeature

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#14]
I am trying to model the functional characteristics of supply, and it seems that I have to do with with an AbstractMediumSupply, according to the UtilityNetwork ADE UML diagram:

![image](https://user-images.githubusercontent.com/13814358/39429494-53117424-4c8b-11e8-99bd-baf2045422e3.png)

It seems that _CityObject gains a property called `mediumSupply`. Does this mean that all `CityObjects` that are extended with the ADE now have this property? I.e., can anything, from a `RoundPipe` to a `MeasurementDevice` gain this property?

I see in the view list we have one called `utn9_medium_supply`, which has a property `cityobject_id`. Is it then appropriate to set this field to the `id` its corresponding network feature?

If this is indeed the case, then I suppose I can then make an entry in `utn9_storage` which then uses its `medium_supply_id` property to link back to its record in `utn9_medium_supply`?

If I am understanding this correctly then I think we can look at the `AbstractMediumSupply` (or conversely, the record in `utn9_medium_supply` as a kind of relation class that links an `AbstractNetworkFeature` (or conversely, any network feature or indeed even a building in the various tables) to a `Storage` and/or a `Supply` element (or conversely, a record in `utn9_storage` and/or a record in `utn9_medium_supply`).

Am I on the right track with this? My goal would be to use elements in `utn9_storage` and `utn9_medium_supply` to model instantaneous state of functional elements, and maintain a permanent link back to the cityobject table via `utn9_medium_supply.cityobject_id = cityobject.id`, and `cityobject.id` should just be the same as `utn9_network_feature.id`, no?

This is made more confusing however because `utn9_network_feature` has a column called `cityobject_id`, but it seems as though its `id` field already links directly back to the `cityobject.id` field.

**Comment by gioagu** [comment]
Hi Isaac,

See my answers inline in red.


I am trying to model the functional characteristics of supply, and it seems that I have to do with with an AbstractMediumSupply, according to the UtilityNetwork ADE UML diagram:

[image]<https://user-images.githubusercontent.com/13814358/39429494-53117424-4c8b-11e8-99bd-baf2045422e3.png>

It seems that _CityObject gains a property called mediumSupply. Does this mean that all CityObjects that are extended with the ADE now have this property? I.e., can anything, from a RoundPipe to a MeasurementDevice gain this property?

Yes. This is what the UML says.

I see in the view list we have one called utn9_medium_supply, which has a property cityobject_id. Is it then appropriate to set this field to the id its corresponding network feature?

Yes, the field cityobject_id corresponds to the „parent_id“ of that mediumsupply.

If this is indeed the case, then I suppose I can then make an entry in utn9_storage which then uses its medium_supply_id property to link back to its record in utn9_medium_supply?

Yes, it is the same principle.

If I am understanding this correctly then I think we can look at the AbstractMediumSupply (or conversely, the record in utn9_medium_supply as a kind of relation class that links an AbstractNetworkFeature (or conversely, any network feature or indeed even a building in the various tables) to a Storage and/or a Supply element (or conversely, a record in utn9_storage and/or a record in utn9_medium_supply).

Yes, but in my understanding this is not meant for the pipes themselves, but – as you say – to model the “point-wise” supply capabilities (or storage capacity) of certain city objects (be it a power plant, or a storage thing).

Am I on the right track with this? My goal would be to use elements in utn9_storage and utn9_medium_supply to model instantaneous state of functional elements, and maintain a permanent link back to the cityobject table via utn9_medium_supply.cityobject_id = cityobject.id, and cityobject.id should just be the same as utn9_network_feature.id, no?

Yes, but WARNING: utn9_network_feature.id is a foreign key to cityobject.id. Whenever you reference a city object, ALWAYS use cityobject.id, not some of the foreign keys in the children tables (like building, etc.). Otherwise you might have problems with the delete functions.

This is made more confusing however because utn9_network_feature has a column called cityobject_id, but it seems as though its id field already links directly back to the cityobject.id field.

WARNING! The utn9_network_feature.cityobject_id implements the „connectedCityObject“ attribute of class „AbstractNetworkFeature“. It is therefore not to be confused with utn9_network_feature.id. Of course, having a manual of the Utility Network for the 3DCityDB would help, I know….

Everything clear?

Giorgio

**Comment by iboates** [comment]
>The utn9_network_feature.cityobject_id implements the „connectedCityObject“ attribute of class „AbstractNetworkFeature“.

If this is the case, is it possible to rename that attribute? Something like `conn_cityobject_id`? It seems like there is a subtle but fundamental difference between this particular implementation of "cityobject_id" and others. Or would that violate the schema standard?

**Comment by gioagu** [comment]
As suggested, renamed this attribute to conn_cityobject_id.

Please help testing (a lot of stuff had to be updated accordingly).
