### ISSUE TITLE
Inconsistency between FME output and database structure in isCorrosive and isExplosive property of LiquidMedium

### ISSUE THREAD

**Issue by iboates** [gioagu/3dcitydb_ade#8]
In the database schema, the `isCorrosive` and `isExplosive` properties of the `LiquidMedium` element, inserted via the `citydb_view.utn9_insert_commodity_liquid_medium()` function, expect that the `is_corrosive` and `is_explosive` parameters be of numeric type.

In the UML structure, these elements are referred to as boolean.

I have noticed that in FME, when writing this element, inputting a "0" or a "1" for these attributes will actually automatically cast them automatically to a string of `"true"` or `"false"`, probably because they defined as boolean in the xsd schema.

Now it isn't much trouble to just catch these values and cast them appropriately, but I just wanted to bring this up in case it would be possible to have these as boolean variables instead, since that is how they are defined in the UML.

**Comment by gioagu** [comment]
Hi,

Short answer: "It's not a bug, it's a feature" [cit.] :-)

Long answer: one of the design criteria for the ADEs in citydb is to stay close to the design of the original 3dctydb. The 3dcitydb implements, also in PostgreSQL, boolean types as numeric (for example, check table "textureparam", column "is_texture_parametrization". I believe this is due to the port from Oracle.
Hence, all boolean types are implemented as numeric.
I'd prefer it as boolean, too, but this would create an asimmetry in the implementation rules.

Regarding FME: maybe you can change the type manually in the writer.
